### ISSUE TITLE
passlib.exc.MissingBackendError: bcrypt: no backends available -- recommend you install one (e.g. 'pip install bcrypt')

### ISSUE THREAD

**Issue by riyazsarah** [Sumanshu-Nankana/FastAPI#1]
Getting this while starting up app from lecture 22

fixed it with installing bcrypt as below. Add it to requirement.txt

 pip install bcrypt

**Comment by Sumanshu-Nankana** [comment]
Thanks, Riyaz.

Yes, you are correct, in official documentation, it's mentioned about 'bcrypt' as well.

https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/?h=passlib#install-passlib

requirements.txt has been updated
